CREATE TABLE `DEPARTMENT` (
    `Deptcode` BIGINT NOT NULL AUTO_INCREMENT,
    `Deptname` VARCHAR(60) NOT NULL UNIQUE,
    `Deptlocation` VARCHAR(60) NOT NULL,
    PRIMARY KEY (`Deptcode`)
) ENGINE = InnoDB;

CREATE TABLE `EMPLOYEE` (
    `Empno` BIGINT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(80) NOT NULL,
    `Job` VARCHAR(40) NOT NULL,
    `hiredate` DATE NOT NULL,
    `salary` DECIMAL(10, 2) NOT NULL,
    `Deptcode` BIGINT NOT NULL,
    PRIMARY KEY (`Empno`)
) ENGINE = InnoDB;

ALTER TABLE `EMPLOYEE`
ADD CONSTRAINT `Deptcode_fk`
FOREIGN KEY (`Deptcode`)
REFERENCES `DEPARTMENT`(`Deptcode`)
ON DELETE RESTRICT ON UPDATE CASCADE;